### ISSUE TITLE
How to reproduce NMF result by setting seed?

### ISSUE THREAD

**Issue by ShixiangWang** [mims-harvard/nimfa#54]
I just see seed options in doc but not how to reproduce the same result. Is there a good way?

**Comment by DanieleSchicchi** [comment]
Hi. 
In nimfa.Nmf you can set the initial factorization of basis matrix W and the initial factorization of mixture matrix H. In that case you must set seed to None.  The type of such matrices can be scipy.sparse or numpy.ndarray or numpy.matrix

for example: 

from nimfa.methods.seeding.nndsvd import Nndsvd
s = Nndsvd()
w,h = s.initialize(your_matrix, rank, options} 
nmf = nimfa.Nmf(V=nmf_matrix, rank=2, W=w, H=h)

for more details look at https://nimfa.biolab.si/nimfa.methods.seeding.nndsvd.html#id4 and 
https://github.com/mims-harvard/nimfa/blob/master/nimfa/models/nmf.py. 

Best,
Daniele

**Comment by ShixiangWang** [comment]
Thanks
