### ISSUE TITLE
Added to conda

### ISSUE THREAD

**Issue by BastianZim** [mims-harvard/nimfa#55]
Hi,

this is more of an FYI than an issue but I just wanted to let the maintainers know that I added nimfa to conda-forge so that it can be downloaded with conda.

The repo is here: https://github.com/conda-forge/nimfa-feedstock

Let me know if anyone of the maintainers here would like to be added as maintainers there or if I should make a PR here to add a badge or install instructions. Otherwise, feel free to just close the issue.

Thanks! 😃

**Comment by marinkaz** [comment]
Hi @BastianZim! We would greatly appreciate it if you made a PR with a badge and install instructions. Thanks!

**Comment by BastianZim** [comment]
Awesome, will do! Just to check, I can see that there are instructions in https://github.com/mims-harvard/nimfa#install and http://ai.stanford.edu/~marinka/nimfa/#installation. 
Are there more locations and would you like me to add the instructions to all of them?

**Comment by BastianZim** [comment]
Just gently pinging this again @marinkaz
